### ISSUE TITLE
Server support for omitting register types from context

### ISSUE THREAD

**Issue by n8tlarsen** [alttch/rmodbus#10]
I typically work in an embedded environment and I appreciate that this crate works with `no_std`, but memory is also constrained so allocating the same size for all register types is not ideal:
```
/// Contains standard Modbus register contexts
#[allow(clippy::module_name_repetitions)]
pub struct ModbusContext {
    pub coils: [bool; CONTEXT_SIZE],
    pub discretes: [bool; CONTEXT_SIZE],
    pub inputs: [u16; CONTEXT_SIZE],
    pub holdings: [u16; CONTEXT_SIZE],
}
```
What would be the best way to implement the following?

1. Allocate different sizes for each register type.
2. Remove one or more of the register types outright. This would also entail returning Modbus exceptions if a client were to try an access a type that has been omitted.

Happy to contribute!

**Comment by divi255** [comment]
v0.7 supports custom context sizes
