### ISSUE TITLE
Make ModbusRequest::parseResponse public

### ISSUE THREAD

**Issue by stefa168** [alttch/rmodbus#15]
Hi, I have been working a lot with this library recently, and I found myself in need of parsing manually the data that I recover from my RTU.

I've seen that there are some parsing methods exposed in `ModbusRequest`, however `parseResponse` isn't among them, and instead is private. Is there any particular reason? If not, could you consider making it public in a future release?

Thanks!

**Comment by divi255** [comment]
Good day,

there are methods to parse bools and u16 from response (and someone added string parser as well). As I understand you want to get response as raw, don't you?

**Comment by stefa168** [comment]
Hi @divi255! Yes, I'd like to get the response as raw, as some devices that I'm using transmit data in other formats.
I saw that `parseResponse` returns the range for the valid response (useful to strip ModbusTcp preamble), so it would be excellent to use for a string slice. Do you think it would be ok to make it a public method?

**Comment by divi255** [comment]
I gonna think about it tomorrow, either make it public or make another function to return raw slices as returning start/end may be confusing. Is it fine for your tasks to get such slices?

**Comment by stefa168** [comment]
Yes, sure, getting directly the slice would be more than enough. Would this also check for the validity of the buffer, like the other parsing methods?

**Comment by divi255** [comment]
yep, for sure

**Comment by divi255** [comment]
I created a function "parse_slice" which does the job.

Available in 0.7.6

**Comment by stefa168** [comment]
Great, thanks!
