### ISSUE TITLE
ModbusFrameBuf is a [u8; 256] but that isn't always enough

### ISSUE THREAD

**Issue by bartios** [alttch/rmodbus#20]
The doc comment at the type states:

```
/// Standard Modbus frame buffer
///
/// As max length of Modbus frame + headers is always 256 bytes or less, the frame buffer is a
/// fixed [u8; 256] array.
```

But that is not true, the PDU is max 253 and the ADU max size changes depending on the protocol, for serial it's 256 but for TCP it's 260. You can see it in the [specification](https://modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf) on page 5.

**Comment by divi255** [comment]
Good day,

as there is only one type for both RTU and TCP, the frame size has been set to max allowed RTU length. I can try increasing it to 260 bytes to use the max possible for TCP, but need to test everything.

**Comment by divi255** [comment]
I found it is possible to just replace references to ModbusFrameBuf in functions/structures with a u8-slice. So the type is no longer mandatory, you can use an array of any desired length if required.

**Comment by bartios** [comment]
Thanks for fixing it this quickly!
