### ISSUE TITLE
Discuss custom modbus context

### ISSUE THREAD

**Issue by bart-sensirion-qm** [alttch/rmodbus#23]
I'm currently trying to use rmodbus at work and am running into some trouble. Where I'm integrating the library the data behind the registers is spread throughout the rest of the code. The library however is written with the assumption that the information will be stored in a ModbusContext. If anything else in the program wants to use this data there are three main choices I can see
1) Keep the ModbusContext as the place where the data is stored, other parts of the program will have to go through the context to read/write it.
2) Keep the data wherever it resides and map the calls from rmodbus to this data.
3) Duplicate the data and try to keep the two copies in sync.

Currently only option 1 is supported (as far as I can see looking at the library) but I think it's self evident that option 2 is preferabele in some cases. I'd like to discuss whether the maintainers would be open to support this usecase and how to best implement this. I would of course help with the work or just send in a PR with the functionality if we can agree on how to implement this.

**Comment by divi255** [comment]
Good day,

the only way I see to use custom layout is to move https://github.com/alttch/rmodbus/blob/master/src/server/context.rs#L234 functionality into a trait

**Comment by bart-sensirion-qm** [comment]
Sorry for the late reply, I blame the holidays.
 Extracting the context functionality into a trait is one option I was thinking about but we also have [rmodbus::server::Changes](https://docs.rs/rmodbus/latest/rmodbus/server/enum.Changes.html) which I think we can work with. I was thinking that maybe we could extend the Frame with some functions to get the "Changes" and "Reads"/"Requested" data. Changes currently doesn't allow access to the data that needs to be written and when making Reads we'd need to feed the data back into a response but I think that's also a real candidate and kind of logical functionality for the Frame to have when it's been parsed. If we go that route than for these kinds of usecases people will just not use the Context type, which I think is also logical if the data is already stored in other parts of the program.

**Comment by divi255** [comment]
if that's enough for your task, feel free to introduce another enum, similar to Changes but for read operations and a new function in ModbusFrame impl
