### ISSUE TITLE
SECS/GEM SEMI?

### ISSUE THREAD

**Issue by han1548772930** [alttch/rmodbus#33]
Hello, I would like to ask if this can be used for SECS/GEM SEMI?

**Comment by divi255** [comment]
Hi. No, this is Modbus crate. Unless you use Modbus over SEMI (I don't know for what but it is possible to use Modbus over almost anything).

**Comment by han1548772930** [comment]
> Hi. No, this is Modbus crate. Unless you use Modbus over SEMI (I don't know for what but it is possible to use Modbus over almost anything).

OK, thanks for your reply
