### ISSUE TITLE
more than 10,000 address support

### ISSUE THREAD

**Issue by zhangchaoza** [alttch/rmodbus#9]
Hi, I've built a modubs tcp server, and I found  rmodubs do not support address over 10,000 . I think it is necessary to access more than 10,000 of a register type.

0x = Coil = 000001-065535
1x = Discrete Input = 100001-165535
3x = Input Register = 300001-365535
4x = Holding Register = 400001-465535

So, how about add a feature to set CONTEXT_SIZE to 65535?

Thanks.Awesome project!

**Comment by divi255** [comment]
Good day,

there are currently two possible context sizes out-of-the-box: 1000 and 10k elements, as we can not specify (yet) particular sizes for static arrays via features.

the best currently recommended way is to fork the crate and set server::context::CONTEXT_SIZE to the desired value. however:

- The context size must be divisible by 8
- In your example coils should start from 0 and end at 65535 = 65536 total
- You must test custom-sized context manually. As the standard tests allocate context in stack, it should be 65536*2+(65536/8)*2 bytes or more.

**Comment by efan-ge** [comment]
Hi,
I just started trying this crate, and then I saw this issue. About CONTEXT, Is the following way OK? 
like:
`pub struct ModbusContext<'a> {
    pub coils: &'a mut [bool]
    pub discretes: &'a [bool]
    pub inputs: &'a [u16]
    pub holdings:&'a mut [u16]
}`

**Comment by Rahix** [comment]
I think const generics may be a solution here.  I tried implementing this here: https://github.com/alttch/rmodbus/commit/69789d8e1cc2ae8b04cf726294ad35624c43680f

It allows downstream code to set the context size without ever touching any cargo features or worse. However, I didn't manage to make it entirely backwards-compatible, unfortunately.  So this change as it stands would be a breaking change...  Not sure if that's worth it here.

**Comment by n8tlarsen** [comment]
@Rahix I definitely think this issue is worth a breaking change. I opened a second issue #10 to address omitting register types entirely, which would be useful in embedded environments running RTU where you can't afford to allocate 1000 registers that aren't used by the device's register map.

**Comment by divi255** [comment]
v0.7 supports custom context sizes
